#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N ax_optimize_v1        # job name

#$ -l h_rt=144:00:00     # hard time limit of 144 hours
#$ -m bea                # send email when finished or aborted
#$ -j y			# merge error and output files into one

#$ -l mem_per_core=6G	# memory requirements per CPU core

#$ -l gpus=2		# number of GPUs
#$ -l gpu_c=6		# GPU minimum capability
#$ -l gpu_type=A100	# GPU type

module load miniconda
conda activate rpm
python ax_optimize.py