#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N Model_v1_itr12       # job name

#$ -l h_rt=120:00:00     # hard time limit of 240 hours
#$ -m bea                # send email when finished or aborted
#$ -j y			# merge error and output files into one

#$ -l mem_per_core=6G	# memory requirements per CPU core

#$ -l gpus=2		# number of GPUs
#$ -l gpu_c=6		# GPU minimum capability
#$ -l gpu_type=L40S	# GPU type

module load miniconda
conda activate rpm
python main.py