#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N v17_itr2_full_actual          # job name

#$ -m bea                # send email when finished or aborted
#$ -j y			# merge error and output files into one

#$ -l mem_per_core=6G	# memory requirements per CPU core
#$ -l gpus=4		# number of GPUs
#$ -l gpu_c=6		# GPU minimum capability
#$ -l gpu_type=A100	# GPU type

module load miniconda
conda activate rpm
python main_masked.py