#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N v17_itr0_full          # job name

#$ -m ea                # send email when finished or aborted 
#$ -j y			# merge error and output files into one

#$ -l mem_per_core=6G	# memory requirements per CPU core
#$ -l gpus=6		# number of GPUs
#$ -l gpu_c=6		# GPU minimum capability

module load miniconda
conda activate rpm
python main_masked.py