#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N v22-itr22_full          # job name

#$ -l h_rt=72:00:00     # hard time limit of 72 hours
#$ -m bea                # send email when finished or aborted
#$ -j y			# merge error and output files into one

#$ -l mem_per_core=6G	# memory requirements per CPU core

#$ -l gpus=3		# number of GPUs
#$ -l gpu_c=6		# GPU minimum capability
#$ -l gpu_type=A100	# GPU type

module load miniconda
conda activate rpm
python main_dynamic.py